version: '3.5'
services:

#####################################################################  
# INFRASTRUCTURE - LOGSTASH 
#####################################################################

#    elasticsearch:
#       image: elasticsearch:7.6.2
#       container_name: elasticsearch
#       ports:
#          - 9200:9200
#          - 9300:9300
#       networks: 
#          - cas-network
#       environment:
#          - discovery.type=single-node
#          
#    logstash:
#       depends_on: 
#          - elasticsearch
#       image: docker.elastic.co/logstash/logstash:7.6.2
#       container_name: logstash
#       ports:
#          - 5000:5000
#       networks: 
#          - cas-network
#       volumes: 
#          - ./logstash.conf:/usr/share/logstash/pipeline/logstash.conf
# 
#    kibana:
#       depends_on: 
#          - elasticsearch
#       image: docker.elastic.co/kibana/kibana:7.6.2
#       container_name: kibana
#       ports:
#          - 5601:5601
#       networks: 
#          - cas-network
#       links:
#          - elasticsearch
         
         
#####################################################################  
# INFRASTRUCTURE - DISCOVERY-SERVER 
#####################################################################

   cas-infra-discovery-server:
      container_name: cas-infra-discovery-server
      build:
         context: ../cas-infra-discovery-server
         dockerfile: Dockerfile
      image: wmaduro/cas-infra-discovery-server:latest
      expose:
         - 8761
      ports:
         - 8761:8761
      networks: 
         - cas-network

#####################################################################  
# INFRASTRUCTURE - CONFIG-SERVER 
#####################################################################

   cas-infra-config-server:
      container_name: cas-infra-config-server
      build:
         context: ../cas-infra-config-server
         dockerfile: Dockerfile
      image: wmaduro/cas-infra-config-server:latest
      networks: 
         - cas-network

      depends_on: 
         - cas-infra-discovery-server
      links:
         - cas-infra-discovery-server
         

#####################################################################  
#  CAS-SERVICES 
#####################################################################

   cas-ms-storage:
      depends_on: 
         - logstash
      container_name: cas-ms-storage
      build:
         context: ../cas-ms-storage
         dockerfile: Dockerfile
      image: wmaduro/cas-ms-storage:latest
      networks: 
         - cas-network
      depends_on: 
         - cas-infra-discovery-server
      links:
         - cas-infra-discovery-server         
            
   cas-ms-file-parser:
      depends_on: 
         - logstash   
      container_name: cas-ms-file-parser
      build:
         context: ../cas-ms-file-parser
         dockerfile: Dockerfile
      image: wmaduro/cas-ms-file-parser:latest
      environment:
         - CAS_MS_STORAGE_HOST=cas-ms-storage
      networks: 
         - cas-network
      depends_on: 
         - cas-infra-discovery-server
      links:
         - cas-infra-discovery-server 
                         
   cas-ms-hand-evaluator:
      depends_on: 
         - logstash   
      container_name: cas-ms-hand-evaluator
      build:
         context: ../cas-ms-hand-evaluator
         dockerfile: Dockerfile
      image: wmaduro/cas-ms-hand-evaluator:latest
      networks: 
         - cas-network
      depends_on: 
         - cas-infra-discovery-server
      links:
         - cas-infra-discovery-server 
          
   cas-ms-hand-mapper:
      depends_on: 
         - logstash   
      container_name: cas-ms-hand-mapper
      build:
         context: ../cas-ms-hand-mapper
         dockerfile: Dockerfile
      image: wmaduro/cas-ms-hand-mapper:latest
      networks: 
         - cas-network
      depends_on: 
         - cas-infra-discovery-server
      links:
         - cas-infra-discovery-server 
                      
   cas-ms-orchestration:
      depends_on: 
         - logstash   
      container_name: cas-ms-orchestration
      build:
         context: ../cas-ms-orchestration
         dockerfile: Dockerfile
      image: wmaduro/cas-ms-orchestration:latest
      environment:
         - CAS_MS_STORAGE_HOST=cas-ms-storage
         - CAS_MS_HAND_EVALUATOR_HOST=cas-ms-hand-evaluator
         - CAS_MS_HAND_MAPPER_HOST=cas-ms-hand-mapper
         - CAS_MS_FILE_PARSER_HOST=cas-ms-file-parser
      networks: 
         - cas-network    
      depends_on: 
         - cas-infra-discovery-server
      links:
         - cas-infra-discovery-server 
      expose:
         - 20009
      ports:
         - 20009:20009
         
networks:
   cas-network:
      name: cas-network
      driver: bridge
    