version: '3.5'
services:

#####################################################################  
# INFRASTRUCTURE - LOGSTASH 
#####################################################################

   elasticsearch:
      image: elasticsearch:7.6.2
      container_name: elasticsearch
      ports:
         - 9200:9200
         - 9300:9300
      networks: 
         - cas-network
      environment:
         - discovery.type=single-node
         
   logstash:
      depends_on: 
         - elasticsearch
      image: docker.elastic.co/logstash/logstash:7.6.2
      container_name: logstash
      ports:
         - 5000:5000
      networks: 
         - cas-network
      volumes: 
         - ./logstash.conf:/usr/share/logstash/pipeline/logstash.conf

   kibana:
      depends_on: 
         - elasticsearch
      image: docker.elastic.co/kibana/kibana:7.6.2
      container_name: kibana
      ports:
         - 5601:5601
      networks: 
         - cas-network
      links:
         - elasticsearch
         

#####################################################################  
# INFRASTRUCTURE - DISCOVERY-SERVER 
#####################################################################

   cas-infra-discovery-server:
      container_name: cas-infra-discovery-server
      build:
         context: ../cas-infra-discovery-server
         dockerfile: Dockerfile
      image: wmaduro/cas-infra-discovery-server:latest
      expose:
         - 8761
      ports:
         - 8761:8761
      networks: 
         - cas-network


#####################################################################  
# INFRASTRUCTURE - API GATEWAY 
#####################################################################

   cas-infra-api-gateway:
      container_name: cas-infra-api-gateway
      build:
         context: ../cas-infra-api-gateway
         dockerfile: Dockerfile
      image: wmaduro/cas-infra-api-gateway:latest
      expose:
         - 8080
      ports:
         - 8080:8080
      networks: 
         - cas-network
      depends_on: 
         - cas-infra-discovery-server
      links:
         - cas-infra-discovery-server
         

#####################################################################  
# INFRASTRUCTURE - CONFIG-SERVER 
#####################################################################

   cas-infra-config-server:
      container_name: cas-infra-config-server
      build:
         context: ../cas-infra-config-server
         dockerfile: Dockerfile
      image: wmaduro/cas-infra-config-server:latest
      networks: 
         - cas-network

      depends_on: 
         - cas-infra-discovery-server
      links:
         - cas-infra-discovery-server
         

         
networks:
   cas-network:
      name: cas-network
      driver: bridge
    