server:
  port: 0 

spring:
  main:
    banner-mode: off
    allow-bean-definition-overriding: true
  outputansi:
    enabled: ALWAYS
  cloud:
    loadbalancer:
      cache:
        ttl: 1s
      ribbon:
        enabled: false


